# Generated by Django 5.1.4 on 2024-12-15 06:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0005_add_menu_items'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='menuitem',
            options={'ordering': ['category', 'name']},
        ),
        migrations.AlterField(
            model_name='menuitem',
            name='description',
            field=models.TextField(),
        ),
    ]
