# Generated by Django 5.1.4 on 2024-12-15 06:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='table',
            options={'ordering': ['number']},
        ),
        migrations.AlterField(
            model_name='table',
            name='number',
            field=models.CharField(max_length=10),
        ),
    ]
